title: Wan Jiang's Blog
description: Record my life and learning
theme: just-the-docs

url: https://Weiwei-Wan.github.io

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/Weiwei-Wan"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

# Friends
friends: [
    {
        title: "Pooki",
        href: "https://bingqixia.github.io"
    },
    {
        title: "siuyunyip",
        href: "https://siuyunyip.github.io/"
    }
]
