title: Wan Jiang's Blog
description: Record my life and learning
theme: just-the-docs

url: https://Weiwei-Wan.github.io

# Friends
friends: [
    {
        title: "Pooki",
        href: "https://bingqixia.github.io"
    },
    {
        title: "siuyunyip",
        href: "https://siuyunyip.github.io/"
    }
]
